name: Build Docker Image Reusable

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Nombre de la imagen Docker a construir (ej. my-app-image)'
        required: true
        type: string
      dockerfile-path:
        description: 'Ruta al Dockerfile dentro del repositorio'
        required: false
        type: string
        default: './Dockerfile'
      context-path:
        description: 'Ruta al contexto de construcción de Docker'
        required: false
        type: string
        default: '.'
      registry-username:
        description: 'Nombre de usuario para el registro de Docker'
        required: true
        type: string

    secrets:
      REGISTRY_TOKEN:
        description: 'Token o contraseña para el registro de Docker'
        required: true

    outputs:
      image-tag:
        description: 'El tag completo de la imagen Docker construida'
        value: ${{ jobs.build_image.outputs.full_image_tag }}

jobs:
  build_image:
    runs-on: ubuntu-latest

    outputs:
      full_image_tag: ${{ steps.vars.outputs.full_image_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.registry-username }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Get current date for image tag
        id: date
        run: echo "DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context-path }}
          file: ${{ inputs.dockerfile-path }}
          push: true
          tags: |
            jhordan01/${{ inputs.image-name }}:latest
            jhordan01/${{ inputs.image-name }}:${{ github.sha }}
            jhordan01/${{ inputs.image-name }}:${{ steps.date.outputs.DATE }}
          outputs: |
            type=image,name=jhordan01/${{ inputs.image-name }},name-canonical=true,push=true

      - name: Set output variables
        id: vars
        run: |
          echo "full_image_tag=jhordan01/${{ inputs.image-name }}:latest" >> $GITHUB_OUTPUT
          echo "image_digest=${{ steps.build_and_push.outputs.digest }}" >> $GITHUB_OUTPUT
